### ISSUE TITLE
No lenses work. They only display a background color. 

### ISSUE THREAD

**Issue by spicyboyozkar** [ptrumpis/snap-camera-server#176]
- Windows 11 
- Snap Camera 1.21 
- Signature Patch Applied: Yes
[Log.txt](https://github.com/user-attachments/files/18270369/Log.txt)
 Followed all directions for install. Docker is up and running, applied signature patch and every single lens that is displayed only shows a solid color in the thumbnail. Clicking on a lens causes it to disappear

**Comment by f-grady** [comment]
I am having the same exact issue on Windows 11 as well OP. Please let me know if you ever figure it out, and I will do the same here!

**Comment by duduws** [comment]
same problem here... in docker logs this:

webproxy-1  | 2025/01/30 00:43:46 [error] 34#34: *20 open() "/var/www/snapcamera/png/e72d2f80-c07f-3fa7-b3cf-60faaf2301b1_320_9d60193b-09c2-47ad-b021-6ff5adeb4094.png" failed (2: No such file or directory), client: 172.18.0.1, server: studio-app.snapchat.com, request: "GET /png/e72d2f80-c07f-3fa7-b3cf-60faaf2301b1_320_9d60193b-09c2-47ad-b021-6ff5adeb4094.png HTTP/1.1", host: "studio-app.snapchat.com:80"
webproxy-1  | 172.18.0.1 - - [30/Jan/2025:00:43:46 +0000] "GET /png/e72d2f80-c07f-3fa7-b3cf-60faaf2301b1_320_9d60193b-09c2-47ad-b021-6ff5adeb4094.png HTTP/1.1" 404 153 "-" "SnapCamera/1.21.0.0 (Windows 11 Version 2009)" "-"
webapp-1    | AbortError: The operation was aborted.
webapp-1    |     at abort (file:///usr/src/app/node_modules/node-fetch/src/index.js:70:18)
webproxy-1  | 172.18.0.1 - - [30/Jan/2025:00:43:52 +0000] "GET /vc/v1/explorer/unlock?uid=58094570875 HTTP/1.1" 200 2 "-" "SnapCamera/1.21.0.0 (Windows 11 Version 2009)" "-"
webapp-1    |     at AbortSignal.abortAndFinalize (file:///usr/src/app/node_modules/node-fetch/src/index.js:89:4)
webapp-1    |     at AbortSignal.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
webapp-1    |     at AbortSignal.dispatchEvent (node:internal/event_target:678:26)
webapp-1    |     at abortSignal (node:internal/abort_controller:292:10)
webapp-1    |     at AbortController.abort (node:internal/abort_controller:323:5)
webapp-1    |     at Timeout._onTimeout (file:///usr/src/app/src/utils/helper.js:57:24)
webapp-1    |     at listOnTimeout (node:internal/timers:559:17)
webapp-1    |     at processTimers (node:internal/timers:502:7) {
webapp-1    |   type: 'aborted'
webapp-1    | }

**Comment by ptrumpis** [comment]
Please try the new server version v3.3.0 and re-create an issue if you continue to have problems.
